### PR TITLE
Add utils

### PR DESCRIPTION
**Pull request by ayalash**
Add utils:
* log_if_slow_context
* deprecated decorator
* deprecation_message

### CODE REVIEW

**Comment by vmalloc** [comment]
Thanks!

**Comment by RazerM** [comment]
I think it would be more pythonic to rename `log_if_slow_context` to `log_if_slow`.

**Comment by RazerM** [comment]
The same could be said for Logbook's `redirected_warnings`, or `redirect_stdout` and `suppress` from the standard library. (Speaking of which, I think Logbook's `redirect_warnings` should have been named `globally_redirect_warnings` or similar, and `redirected_warnings` named `redirect_warnings`, but it's too late due to backwards compatibility)

Ultimately one has to read the documentation to know how a function should be used.

**Comment by vmalloc** [comment]
I think you're just strengthening my point :-)

`redirect_warnings` is an imperative verb - and indeed is not a context and should not be used with `with`. It internally calls `__enter__` of  `redirected_warnings` which *is* a context, and therefore not named as an imperative.

I'm not sure what you mean by `suppress` from the standard library, but if I had to guess it's a function (otherwise it would be called `suppressed` or something similar).

**Comment by vmalloc** [comment]
Oh - I found it - in Python 3. Well, the standard library isn't always the perfect example for naming convention (case in point the terrible mix of camelcasing and underscores, and even foolish use of properties instead of functions).

It is true that one often needs the documentation, but I think we should still try to make the code readable without docs.

Even without docs, stumbling upon `redirected_warnings` without the use of `with` clearly sticks out to the eye as improper usage, while if it were phrased like a verb you'd never be sure without looking at the source or docs.

**Comment by RazerM** [comment]
I disagree, if only because it feels like doing `logger = LoggerClass()`. I agree that `redirected_warnings` looks weird on it's own, though.

Would `logged_if_slow` be better? `suppressed_deprecations`?

**Comment by vmalloc** [comment]
I think `suppressed_deprecations` is a good name. I will switch to it.

About `logged_if_slow` I'm not so sure. @ayalash what do you think?

**Comment by ayalash** [comment]
Sure, `suppressed_deprecations` & `logged_if_slow` sounds good

**Comment by vmalloc** [comment]
Ok, will change

**Pull request merged**
