### PR TITLE
Improve logging compatibility

### LINKED ISSUE #151: Exception in LoggingCompatRecord for mapping keys
Example:
```
logger = logging.getLogger("test")
logger.setLevel("DEBUG")
logger.addHandler(RedirectLoggingHandler())

with logbook.StderrHandler():
    logger.debug("test map %(name)s", {"name": "mapname"})     
    # raise exception in LoggingCompatRecord:
   #Traceback (most recent call last):
    #   File "D:\bin\Python34\lib\site-packages\logbook\base.py", line 515, in message
    #    return self._format_message(self.msg, *self.args, **self.kwargs)
    #  File "D:\bin\Python34\lib\site-packages\logbook\compat.py", line 66, in _format_message
    #    return msg % tuple(args)
    # TypeError: format requires a mapping
```

The quote from "logging/\_\_init\_\_.py"
>
        #
        # The following statement allows passing of a dictionary as a sole
        # argument, so that you can do something like
        #  logging.debug("a %(a)d b %(b)s", {'a':1, 'b':2})
        # Suggested by Stefan Behnel.
        # Note that without the test for args[0], we get a problem because
        # during formatting, we test to see if the arg is present using
        # 'if self.args:'. If the event being logged is e.g. 'Value is %d'
        # and if the passed arg fails 'if self.args:' then no formatting
        # is done. For example, logger.warning('Value is %d', 0) would log
        # 'Value is %d' instead of 'Value is 0'.
        # For the use case of passing a dictionary, this should not be a
        # problem.
        # Issue #21172: a request was made to relax the isinstance check
        # to hasattr(args[0], '__getitem__'). However, the docs on string
        # formatting still seem to suggest a mapping object is required.
        # Thus, while not removing the isinstance check, it does now look
        # for collections.Mapping rather than, as before, dict.
        if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
            and args[0]):
            args = args[0]

### PR DESCRIPTION
**Pull request by RazerM**
Fixes #151

### CODE REVIEW

**Comment by vmalloc** [comment]
Thanks!

**Comment by jstewmon** [comment]
@vmalloc , any idea when the next pypi release might be? This issue has been fixed for 7 months, but not released.

**Comment by vmalloc** [comment]
I guess now is as good a time as any. Released 1.0.0...

**Comment by jstewmon** [comment]
Woot! Thanks!

**Pull request merged**
