### PR TITLE
pep8 changes

### PR DESCRIPTION
**Pull request by staranjeet**
This PR fixes some of the warnings generated while running pep8 test. It does not removes those warnings completely. There are some cases where I feel that those warnings can be ignored. You can check it yourself. Let me know if you need any more changes.

### CODE REVIEW

**Comment by RazerM** [comment]
Nice work.

If I can give some constructive criticism, I think you're overusing continuation lines.

Rather than this:

```python
from .base import LogRecord, Logger, LoggerGroup, NestedSetup, \
    Processor, Flags, get_level_name, lookup_level, dispatch_record, \
    CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE, NOTSET, \
    set_datetime_format
```

I'd prefer this:

```python
from .base import (
    LogRecord, Logger, LoggerGroup, NestedSetup, Processor, Flags,
    get_level_name, lookup_level, dispatch_record, CRITICAL, ERROR, WARNING,
    NOTICE, INFO, DEBUG, TRACE, NOTSET, set_datetime_format)
```

**Comment by staranjeet** [comment]
Yeah initially I was doing the same but then I realized that the whole project is following the same convention. No issues I will rectify these.

**Comment by staranjeet** [comment]
@RazerM : In `docs/conf.py`, I found out that the below warning is very common. 
`E265 block comment should start with '# '`

I think this should be ignored because # with no space is for heading, whereas pep8 test is considering it as a python comment.
What say?

**Comment by RazerM** [comment]
I would place a space between `#` and code, this is what most editors do too.

```python
# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'
```

```python
# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'
```

Plus, it looks cleaner

**Comment by vmalloc** [comment]
Thanks for contributing!

**Comment by staranjeet** [comment]
@RazerM : got it. I will fix those warnings now 

@vmalloc : anytime.

**Comment by wong2** [comment]
:clap:

**Pull request merged**
