### PR TITLE
Replace ExtraDict with defaultdict

### PR DESCRIPTION
**Pull request by thedrow**
I don't really understand why ExtraDict is needed. It duplicates the same functionality as defaultdict.
I just removed it from the code base and replaced it with defaultdict.

### CODE REVIEW

**Comment by thedrow** [comment]
I'm able to run the tests locally. What's wrong?

**Comment by vmalloc** [comment]
From a quick glance it looks like the import reordering caused a cyclic import dependency (at least looking at the Travis failure)

**Comment by vmalloc** [comment]
Also reproduces on my end (try using a clean virtualenv - you may be getting the imports from a locally installed version)

**Comment by thedrow** [comment]
I also fixed the typo in the comment.

**Comment by thedrow** [comment]
Now isort will not try to sort this import forever.

**Comment by vmalloc** [comment]
Thanks for contributing!

**Pull request merged**
