### PR TITLE
Mark temperamental test as xfail

### PR DESCRIPTION
**Pull request by RazerM**
Also forgot to push one commit for #191 which I've added here...

Hopefully AppVeyor passes and it can be merged

### CODE REVIEW

**Comment by RazerM** [comment]
It seems #175 wasn't fixed after all—there should be a check similar to Travis

**Comment by RazerM** [comment]
I'm getting a test failure in `test_logged_if_slow_did_not_reached`. Let's hold off on merge until I see what's going on.

**Comment by RazerM** [comment]
Ok I don't know what's going on with the test that failed, it's back to passing again. This can be merged, if all looks fine to you.

**Comment by vmalloc** [comment]
thanks!

**Pull request merged**
