### PR TITLE
Added support for checking if trace logs have been emitted

### PR DESCRIPTION
**Pull request by thedrow**
This method was missing so I added it.

### CODE REVIEW

**Comment by thedrow** [comment]
I can add test coverage for this if needed.

**Comment by vmalloc** [comment]
If possible, a test or two to cover the new functionality would be much appreciated. Thanks!

**Comment by thedrow** [comment]
@vmalloc Can you please merge this?
If you don't mind releasing as well, I'd be grateful.

**Comment by vmalloc** [comment]
Merged. Thanks a lot!

Will release 1.4.0 containing it soon.

**Pull request merged**
