### PR TITLE
fixes pep8 warnings

### PR DESCRIPTION
**Pull request by staranjeet**

### CODE REVIEW

**Comment by vmalloc** [comment]
Hi, Can you please rebase over latest master?

**Comment by staranjeet** [comment]
I rebased, but I am unable to push, Getting the error that tip of my current branch is behind its remote counterpart. Any help?

**Comment by vmalloc** [comment]
Merged manually. Thanks!

**Comment by staranjeet** [comment]
@vmalloc : How can i contact you apart from github or twitter?

**Comment by vmalloc** [comment]
vmalloc _at_ gmail.com.

Here's a nice trick you usually perform - clone a repo, look at the email address on the commits :-)

**Pull request merged**
